name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: " login to dockerhub"
      run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: " building docker "
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/climan .
    - name: " pushing to docker hub "
      run: docker push ${{ secrets.DOCKER_USERNAME}}/climan
